/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ModelRouteImport } from './routes/model'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AiOsRouteImport } from './routes/ai-os'
import { Route as AcquisitionsRouteImport } from './routes/acquisitions'
import { Route as IndexRouteImport } from './routes/index'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AiOsRoute = AiOsRouteImport.update({
  id: '/ai-os',
  path: '/ai-os',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsRoute = AcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/ai-os': typeof AiOsRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/leadership': typeof LeadershipRoute
  '/model': typeof ModelRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/ai-os': typeof AiOsRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/leadership': typeof LeadershipRoute
  '/model': typeof ModelRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRoute
  '/ai-os': typeof AiOsRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/leadership': typeof LeadershipRoute
  '/model': typeof ModelRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisitions'
    | '/ai-os'
    | '/companies'
    | '/contact'
    | '/insights'
    | '/leadership'
    | '/model'
    | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisitions'
    | '/ai-os'
    | '/companies'
    | '/contact'
    | '/insights'
    | '/leadership'
    | '/model'
    | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/acquisitions'
    | '/ai-os'
    | '/companies'
    | '/contact'
    | '/insights'
    | '/leadership'
    | '/model'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionsRoute: typeof AcquisitionsRoute
  AiOsRoute: typeof AiOsRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  LeadershipRoute: typeof LeadershipRoute
  ModelRoute: typeof ModelRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-os': {
      id: '/ai-os'
      path: '/ai-os'
      fullPath: '/ai-os'
      preLoaderRoute: typeof AiOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionsRoute: AcquisitionsRoute,
  AiOsRoute: AiOsRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  LeadershipRoute: LeadershipRoute,
  ModelRoute: ModelRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
